targets:
  $default:
    builders:
      rive_viewmodel_generator:
        enabled: true
        generate_for:
          include:
            - test/*

builders:
  rive_viewmodel_generator:
    import: "package:rive_viewmodel_generator/builder.dart"
    builder_factories: ["riveViewModelGenerator"]
    build_extensions: {".dart": [".rive_viewmodel_generator.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
    runs_before: ['riverpod']